#!/bin/bash
set -x

SOURCES_FILE=/etc/apt/sources.list.d/zulip.list
zulip_source_hash=`shasum $SOURCES_FILE`


SCRIPTS_PATH="$(dirname $(dirname $0))"
# Add the apt keys
apt-key add "$SCRIPTS_PATH"/setup/zulip-ppa.asc
apt-key add "$SCRIPTS_PATH"/setup/pgroonga-ppa.asc

if [ "$zulip_source_hash" = "`shasum $SOURCES_FILE`" ]; then
    echo "zulip.list file did not change; skipping apt-get update"
else
    brew update
fi
